name: Continuous cron job
on:
  workflow_dispatch:
  schedule:
    - cron:  '*/1 * * * *'
    
jobs:
  cron-job:
    name: Run cron job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
        
      - name: Hello world
        run: echo "Hello world!"
