name: PR build and test

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
    - '**.md'

jobs:
  build-test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false  # ensures the entire test matrix is run, even if one permutation fails
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v2
